spring:
  application:
    name: notice
#  profiles:
#    active: local

springdoc:
  api-docs:
    path: /v3/api-docs # default value
    groups:
      enabled: true # API grouping

  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha # 태그 정렬 방식 (알파벳순)
    operations-sorter: alpha # 메서드 정렬 방식
    display-request-duration: true # 요청에 소요된 시간 표시
    doc-expansion: none # 문서 초기 펼침 상태