server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins:
              - "http://localhost:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers:
              - Content-Type
              - Authorization
              - X-Requested-With
            allow-credentials: true
      routes:
        - id: hr
          uri: lb://HR
          # k8s 클러스터 내에서 다른 서비스를 지목하기위한 DNS 명명 규칙.
          # <service-name>.<namespace>.svc.cluster.local:port
#          uri: http://user-service.default.svc.cluster.local:8081
          predicates:
            - Path=/hr/**
          filters:
            - AuthorizationHeaderFilter

        - id: notice
          uri: lb://NOTICE
          #          uri: http://user-service.default.svc.cluster.local:8081
          predicates:
            - Path=/notice/**
          filters:
            - AuthorizationHeaderFilter

        - id: community
          uri: lb://NOTICE
          #          uri: http://user-service.default.svc.cluster.local:8081
          predicates:
            - Path=/community/**
          filters:
            - AuthorizationHeaderFilter

        - id: approval
          uri: lb://APPROVAL
          #          uri: http://user-service.default.svc.cluster.local:8081
          predicates:
            - Path=/approval/**
          filters:
            - AuthorizationHeaderFilter