#
spring:
  application:
    name: hr
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.web.tomcat.TomcatMetricsAutoConfiguration
p6spy:
  config:
    registermbeans: false

weather:
  api:
    key: ZXtHl7IjyIssn+uPYkhLiyHlbIyxO1Zj89v0YwTWPGkSka2+/t47TsClb/2z8sfd5pLYfRfGmyVC6aMM4UgrZg==
    base-url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
#  profiles:
#    active: local