server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      enabled: false #config server 사용 안함 (서버를 돌릴 필요까지 없음)
#      server:
#        native:
#          search-locations: "/Users/dominus_pacem/Desktop/HRHub/HRHub-Config"

#  "file:///C:/Users/dutls/Desktop/work_place/yhj_Team_Project/hrhub-config" 노트북 경로
#  "/Users/dominus_pacem/Desktop/HRHub/HRHub-Config pc" 경로